name: Unit Tests
description: Run Node.js unit tests

runs:
  using: "composite"
  steps:
    - run: cd backend
      shell: bash
    - run: npm install
      shell: bash
    - run: npm run test:unit
      shell: bash