version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-database}
      DB_NAME: ${DB_NAME:-database}
      DB_USER: ${DB_USER:-database}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD:-database}
      JWT_SECRET: ${JWT_SECRET:-verysecurepassword}
      DERIVATION_ROUND: ${DERIVATION_ROUND:-100000}
      VAULT_SECRET: ${VAULT_SECRET:-verysecurepassword}
      ADMIN_ROLE: ${ADMIN_EMAIL:-admin}
      ADMIN_USERNAME: ${ADMIN_ROLE:-admin}
      ADMIN_PASSWORD: ${ADMIN_ROLE:-admin}
      ADMIN_ROLE: ${ADMIN_ROLE:-super-manager}
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-database}
      DB_NAME: ${DB_NAME:-database}
      DB_USER: ${DB_USER:-database}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD:-database}
    volumes:
      - ./database/postgres-init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./database:/datamodel
      - pg_data:/var/lib/postgresql/data
    restart: always

  swagger-ui:
    image: swaggerapi/swagger-ui:v4.1.0
    volumes:
      - ./Swagger/docapi.json:/api.json
    environment:
      SWAGGER_FILE: /api.json
      SWAGGER_JSON: /api.json
    ports:
      - 8081:8080

volumes:
  pg_data: