version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD:-postgres}
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD:-postgres}
    volumes:
      - ./database/postgres-init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./database/tables:/datamodel
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data: