name: Deploy
description: Deploy

inputs:
  SSH_HOST:
    description: SSH Host
    required: true
  SSH_DEPLOY_KEY:
    description: SSH DEPLOY KEY
    required: true
  SSH_USERNAME:
    description: SSH USERNAME
    required: true
  SSH_PORT:
    description: SSH PORT
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa,dsa "${{ inputs.SSH_HOST }}" 2>/dev/null > ~/.ssh/known_hosts
        echo -e "${{ inputs.SSH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval `ssh-agent -s`
        ssh-add ~/.ssh/id_rsa
        ssh "${{ inputs.SSH_USERNAME }}@${{ inputs.SSH_HOST }}" "whoami"
      shell: bash