name: Lint
description: Lint

runs:
  using: "composite"
  steps:
    - run: cd backend
      shell: bash
    - run: npm install
      shell: bash
    - run: npm run test:lint
      shell: bash
      
    